### ISSUE TITLE
Validation dosen't work

### ISSUE THREAD

**Issue by EmeraldWeb** [michael-ciniawsky/posthtml-w3c#2]
I added an example archive.
Instead of getting an error message (tag `img` without `alt` attribute ), I get the following message in the console:

`PostHTML W3C Validation`
`undefined  0 Errors`

[posthtml-w3c.zip](https://github.com/posthtml/posthtml-w3c/files/3540728/posthtml-w3c.zip)

**Comment by Scrum** [comment]
@EmeraldWeb Hi, I'm glad that you are interested in this package.

I will try to understand the problem in the very near future.
